### PR TITLE
new-blogpost-konfigkontrollsky3

### PR DESCRIPTION
**Pull request by kjehanse**
Kjetil writing new blogpost: Konfigurasjonskontroll for økt sikkerhet i skyløsninger – del 3

To be published on Monday 09.01.22? 

Signed-off-by: Kjetil Stubbom Hansen <kjetil.stubbom.hansen@amesto.no>

### CODE REVIEW

**Review by remiks — CHANGES_REQUESTED** [review]
I have read the text and tested local build. The text is nice and to the point.

Two things need to be fixed.
1. The hero image need to be 950x530 - (We also need to update the readme file).
2. On the "Noen råd i den forbindelse" you need to change to hyphens instead og bullets as this screws up the formatting and puts it in a code block.
image

**Comment by kjehanse** [comment]
> I have read the text and tested local build. The text is nice and to the point.
> 
> Two things need to be fixed.
> 
> 1. The hero image need to be 950x530 - (We also need to update the readme file).
> 2. On the "Noen råd i den forbindelse" you need to change to hyphens instead og bullets as this screws up the formatting and puts it in a code block.
>    image


Thanks, i will look into this.

**Comment by kjehanse** [comment]
Please have a look @remiks

**Comment by remiks** [comment]
Nope. 
1. The image is wrong proportion. I made a new one for you here:
astronaut-lego-950px

2. You need to have single hyphens in a bullet list, double "--" is not valid markdown.
image

**Comment by kjehanse** [comment]
Thanks @remiks, please have a look now.

**Review by remiks — APPROVED** [review]

**Pull request merged**
