### PR TITLE
feat: update to theme v0.5.1 of Pitayan

### LINKED ISSUE #44: Update to v0.5.1 of Pitayan theme
Update to release 0.5.1 og Pitayan theme and write som update routines in our readme file so its easier to update theme next time. 
https://github.com/Pitayan/gatsby-theme-pitayan

### PR DESCRIPTION
**Pull request by remiks**

### CODE REVIEW

**Comment by remiks** [comment]
@alegri90 tar du en titt og prøver å bygge deg denne lokalt. Skal funke fint.

**Comment by remiks** [comment]
@roberthstrand , can you do a local test of this?

**Review by roberthstrand — APPROVED** [review]
Running `gatsby develop` worked for me, after installing _gatsby-plugin-sitemap_. As far as I can tell, this should work fine.

**Comment by remiks** [comment]
@roberthstrand Is there anything in the actions/build we need to change? Im thinking specifically about the line `npm install --save-dev gatsby @pitayan/gatsby-theme-pitayan react@18 react-dom@18 --legacy-peer-deps` as it`s a new version of Gatsby..

**Pull request merged**
